#!/usr/bin/env python3
"""
Embeds SPIR-V shaders into static C++ arrays in src/shaders_embedded.hpp
"""

import subprocess
from pathlib import Path

root = Path(__file__).parent.parent
shaders_dir = root / "shaders"
src_dir = root / "src"
out_header = src_dir / "shaders_embedded.hpp"

shader_files = [
    ("cq_hecs_core", shaders_dir / "cq_hecs_core.comp"),
    ("explosion_shield", shaders_dir / "explosion_shield.comp"),
    ("cuckoo_prune", shaders_dir / "cuckoo_prune.comp"),
]

embedded_data = {}

for name, comp_path in shader_files:
    spv_path = shaders_dir / f"{name}.spv"
    # Compile shader to SPIR-V binary
    res = subprocess.run(["glslc", str(comp_path), "-o", str(spv_path)], capture_output=True, text=True)
    if res.returncode != 0:
        raise RuntimeError(f"Failed to compile {comp_path}: {res.stderr}")

    # Read binary bytes
    with open(spv_path, "rb") as f:
        bytes_data = f.read()

    # Convert to uint32_t array
    assert len(bytes_data) % 4 == 0, f"SPIR-V size {len(bytes_data)} not multiple of 4"
    uint32_vals = []
    for i in range(0, len(bytes_data), 4):
        val = int.from_bytes(bytes_data[i:i+4], byteorder="little")
        uint32_vals.append(f"0x{val:08x}")
    embedded_data[name] = uint32_vals

with open(out_header, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by scripts/embed_shaders.py - DO NOT EDIT MANUALLY\n")
    f.write("#pragma once\n#include <cstdint>\n#include <cstddef>\n\n")
    f.write("namespace cq_hecs::embedded_shaders {\n\n")

    for name, vals in embedded_data.items():
        f.write(f"inline const uint32_t {name}_spv[] = {{\n")
        # Write 8 words per line
        for i in range(0, len(vals), 8):
            chunk = ", ".join(vals[i:i+8])
            f.write(f"    {chunk},\n")
        f.write("};\n")
        f.write(f"inline const size_t {name}_spv_size = sizeof({name}_spv);\n\n")

    f.write("} // namespace cq_hecs::embedded_shaders\n")

print(f"[OK] Generated {out_header} with {len(shader_files)} embedded shaders.")
